const { _electron: electron } = require('playwright');
const { spawn, spawnSync } = require('node:child_process');
const { mkdtemp, rm, mkdir, readFile, writeFile } = require('node:fs/promises');
const { tmpdir } = require('node:os');
const path = require('node:path');
const net = require('node:net');
const assert = require('node:assert/strict');

async function freePort() {
  const server = net.createServer();
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  const port = server.address().port;
  await new Promise((resolve) => server.close(resolve));
  return port;
}
async function main() {
  const root = path.resolve(__dirname, '../..');
  const temporary = await mkdtemp(path.join(tmpdir(), 'evidencemesh-'));
  const port = await freePort();
  const origin = `http://127.0.0.1:${port}`;
  const python = process.env.EVIDENCEMESH_PYTHON ?? path.join(root, '.venv', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python');
  const backend = spawn(python, ['-m', 'uvicorn', 'api.main:app', '--host', '127.0.0.1', '--port', String(port)], {
    cwd: root, env: { ...process.env, EVIDENCEMESH_DB: path.join(temporary, 'test.sqlite3') }, stdio: ['ignore', 'pipe', 'pipe'],
  });
  let logs = '';
  backend.stdout.on('data', (chunk) => { logs += chunk; });
  backend.stderr.on('data', (chunk) => { logs += chunk; });
  backend.on('error', (error) => { logs += String(error); });
  let desktop;
  try {
    let ready = false;
    for (let attempt = 0; attempt < 80; attempt++) {
      if (backend.exitCode !== null) throw new Error(`Backend exited: ${logs}`);
      try { ready = (await fetch(`${origin}/health`)).ok; } catch { /* bounded startup polling */ }
      if (ready) break;
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
    assert(ready, `API did not start: ${logs}`);
    const executablePath = process.env.EVIDENCEMESH_DESKTOP_EXECUTABLE;
    const args = executablePath ? [] : [path.resolve(__dirname, '..')];
    // Only the root-owned CI container needs this. Normal desktop launch keeps Chromium sandboxing.
    if (process.platform === 'linux' && process.getuid?.() === 0) args.unshift('--no-sandbox');
    desktop = await electron.launch({ executablePath, args, env: { ...process.env, ELECTRON_RUN_AS_NODE: '', EVIDENCEMESH_API: origin } });
    const window = await desktop.firstWindow();
    await desktop.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setContentSize(1440, 900));
    await window.waitForFunction(() => innerWidth === 1440 && innerHeight === 900);
    const errors = [];
    window.on('pageerror', (error) => errors.push(String(error)));
    const screenshots = path.resolve(__dirname, '../test-results');
    await mkdir(screenshots, { recursive: true });
    const shot = async (name) => window.screenshot({ path: path.join(screenshots, name), fullPage: true });
    const navigate = async (view) => window.locator(`#navigation [data-view="${view}"]`).click();
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Engine connected'));
    await window.click('#load-sample');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Loaded 15 events'));
    assert.equal(await window.locator('#source-table tbody tr').count(), 3);
    await shot('01-case-evidence.png');
    await navigate('evidence');
    assert.equal(await window.locator('#evidence-table tbody tr').count(), 15);
    await shot('02-evidence-table.png');
    await navigate('processes');
    assert.equal(await window.locator('#process-table tbody tr').count(), 4);
    await shot('03-process-list.png');
    await window.locator('#process-table [data-event-id="MEM-PS"]').focus();
    await window.keyboard.press('Enter');
    assert.match(await window.locator('#inspector-content').innerText(), /powershell.exe -File/);
    assert.match(await window.locator('#root-summary').innerText(), /4120/);
    await shot('04-process-detail.png');
    await window.click('#analyze');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Analysis complete'));
    assert.equal(await window.locator('#correlation-table tbody tr').count(), 16);
    await shot('05-correlations.png');
    await window.locator('#correlation-table [data-key="MEM-SOCKET:NET-TLS"]').click();
    assert.match(await window.locator('#inspector-content').innerText(), /same socket tuple/);
    assert.match(await window.locator('#inspector-content').innerText(), /90/);
    assert.match(await window.locator('#inspector-content').innerText(), /PCAP/);
    await shot('06-correlation-inspector.png');
    await window.click('[data-inspector="provenance"]');
    assert.match(await window.locator('#inspector-content').innerText(), /Original row/);
    await shot('07-provenance.png');
    await navigate('timeline');
    assert.equal(await window.locator('#timeline-table tbody tr').count(), 9);
    assert.equal(await window.locator('#timeline-table [data-event-id^="NOISE"]').count(), 0);
    await shot('08-timeline.png');
    await window.uncheck('#incident-only');
    assert.equal(await window.locator('#timeline-table tbody tr').count(), 15);
    await navigate('graph');
    assert.equal(await window.locator('.graph-node').count(), 9);
    assert.equal(await window.locator('.graph-edge').count(), 16);
    await window.locator('.graph-node[data-node-id="event:MEM-PS"]').focus();
    await window.keyboard.press('Enter');
    assert.match(await window.locator('#inspector-content').innerText(), /powershell.exe/);
    await shot('09-incident-graph.png');
    await window.getByRole('button', { name: 'Expand graph', exact: true }).click();
    await shot('09b-incident-graph-expanded.png');
    await window.getByRole('button', { name: 'Show inspector', exact: true }).click();
    await window.getByRole('button', { name: 'Expand graph', exact: true }).click();
    await window.locator('.graph-node[data-node-id="event:MEM-PS"]').focus();
    await window.keyboard.press('Enter');
    assert(await window.locator('#inspector-content').isVisible());
    assert.equal(await window.getByRole('button', { name: 'Expand graph', exact: true }).count(), 1);
    await shot('sample-analysis.png');
    assert.equal(await window.evaluate(() => typeof window.require), 'undefined');
    assert.deepEqual(errors, []);
    await navigate('processes');
    await window.fill('#search', 'notepad');
    assert.equal(await window.locator('#process-table tbody tr').count(), 1);
    await window.click('#process-table [data-event-id="NOISE-MEM"]');
    await window.click('#analyze');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('No matching evidence'));
    assert.equal(await window.locator('#correlation-table tbody tr').count(), 0);
    await window.click('#brand');
    await window.fill('#case-name', 'JSON Import Verification');
    await window.click('#create-case');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Loaded 0 events'));
    // Only the native file selection is automated; real files, IPC, validation, storage and rules run unchanged.
    const sampleFiles = ['memory', 'disk', 'network'].map((source) => path.join(root, 'samples/sample_case', `${source}_events.json`));
    await desktop.evaluate(({ dialog }, files) => {
      dialog.showOpenDialog = async () => ({ canceled: false, filePaths: files });
    }, sampleFiles);
    await window.click('#import-events');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Imported 15 events'));
    await navigate('processes');
    await window.click('#process-table [data-event-id="MEM-PS"]');
    await window.click('#analyze');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Analysis complete'));
    assert.equal(await window.locator('#correlation-table tbody tr').count(), 16);
    const cases = await (await fetch(`${origin}/cases`)).json();
    const importedCase = cases.find((item) => item.name === 'JSON Import Verification');
    const imported = await (await fetch(`${origin}/cases/${importedCase.case_id}/events`)).json();
    assert(imported.every((event) => event.attributes.import_reference.sha256.length === 64));
    const memory = spawnSync(python, ['-m', 'engine.cli', 'import-memory', path.join(root, 'tests/fixtures/volatility'),
      '--image-id', 'ui-fixture-memory', '--extracted-at', '2026-09-16T09:35:00Z', '--hostname', 'workstation-01',
      '--volatility-version', '2.28.2', '--name', 'Volatility UI Verification', '--db', path.join(temporary, 'test.sqlite3')], { cwd: root, encoding: 'utf8' });
    assert.equal(memory.status, 0, memory.stderr);
    const memoryCase = JSON.parse(memory.stdout).case_id;
    const disk = JSON.parse(await readFile(path.join(root, 'samples/sample_case/disk_events.json'), 'utf8'));
    const network = JSON.parse(await readFile(path.join(root, 'samples/sample_case/network_events.json'), 'utf8'));
    const appended = await fetch(`${origin}/cases/${memoryCase}/events`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify([...disk, ...network]) });
    assert.equal(appended.status, 201);
    await window.click('#refresh');
    await window.waitForFunction(() => !document.querySelector('#refresh').disabled);
    await window.selectOption('#case-select', memoryCase);
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Loaded 18 events'));
    await navigate('processes');
    assert.equal(await window.locator('#process-table tbody tr').count(), 3);
    await window.locator('#process-table tbody tr').filter({ hasText: 'powershell.exe' }).click();
    await window.click('[data-inspector="provenance"]');
    assert.match(await window.locator('#inspector-content').innerText(), /windows.cmdline/);
    assert.match(await window.locator('#inspector-content').innerText(), /windows.pslist/);
    assert.match(await window.locator('#inspector-content').innerText(), /windows.pstree/);
    assert.match(await window.locator('#inspector-content').innerText(), /ui-fixture-memory/);
    await shot('10-volatility-provenance.png');
    await window.click('#analyze');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Analysis complete'));
    assert((await window.locator('#correlation-table tbody tr').count()) > 0);
    await navigate('dlls');
    assert.equal(await window.locator('#evidence-table tbody tr').count(), 3);
    await window.locator('#evidence-table tbody tr').first().click();
    assert.match(await window.locator('#inspector-content').innerText(), /Base address/);
    await shot('11-volatility-dlls.png');
    await navigate('graph');
    await window.click('[data-graph-mode="entities"]');
    assert((await window.locator('.graph-hit[aria-label^="PARENT_OF"]').count()) === 2);
    assert((await window.locator('.graph-hit[aria-label^="LOADED"]').count()) === 3);
    await shot('12-process-dll-parent-graph.png');
    await navigate('http');
    assert.match(await window.locator('#workspace-content').innerText(), /No http observations/);
    const overflow = await window.evaluate(() => document.documentElement.scrollWidth > window.innerWidth || document.documentElement.scrollHeight > window.innerHeight);
    assert.equal(overflow, false, 'Workstation shell must fit the desktop viewport');
    assert.deepEqual(errors, []);
    await window.click('#brand');
    await window.fill('#case-name', 'Cross-Source Artifact Imports');
    await window.click('#create-case');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Loaded 0 events'));
    const cross = path.join(root, 'samples/cross_source');
    const importArtifact = async (kind, filename, format, acquisition, host = 'workstation-01') => {
      await window.fill('#import-acquisition_id', acquisition);
      await window.fill('#import-extracted_at', '2026-09-16T09:35:00Z');
      await window.fill('#import-hostname', host);
      await window.fill('#import-volume_id', 'volume-C');
      await window.fill('#import-recovered_directory', path.join(cross, 'memory/recovered'));
      if (format) await window.selectOption('#disk-format', format);
      if (format === 'file') await window.fill('#import-logical_path', 'C:\\Users\\test\\AppData\\Local\\Temp\\a.ps1');
      await desktop.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, filename);
      await window.click(`#import-${kind}`);
      await window.waitForFunction(() => !document.querySelector('#refresh').disabled);
      assert.match(await window.locator('#status').innerText(), /SUCCESS: imported/);
    };
    await importArtifact('memory', path.join(cross, 'memory/volatility'), null, 'cross-memory');
    await shot('13-memory-artifact-import.png');
    for (const format of ['mft', 'usn', 'prefetch', 'evtx', 'amcache']) {
      await importArtifact('disk', path.join(cross, 'disk/artifacts', `${format}.json`), format, 'cross-disk');
    }
    await importArtifact('disk', path.join(cross, 'disk/artifacts/a.ps1'), 'file', 'cross-disk');
    await importArtifact('network', path.join(cross, 'network/traffic.pcapng'), null, 'cross-network', '');
    await shot('14-cross-source-imports.png');
    await navigate('parser-runs');
    assert.equal(await window.locator('#parser-runs-table tbody tr').count(), 28);
    await window.locator('#parser-runs-table tbody tr').filter({ hasText: 'TsharkAdapter' }).click();
    assert.match(await window.locator('#inspector-content').innerText(), /SUCCESS/);
    await shot('15-parser-runs.png');
    await navigate('processes');
    const powerShell = () => window.locator('#process-table tbody tr').filter({ hasText: 'powershell.exe' }).first();
    await powerShell().click();
    await window.click('#analyze');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('Analysis complete'));
    const completeStatus = await window.locator('#status').innerText();
    assert.match(completeStatus, /34 related events/);
    assert.equal(await window.locator('#correlation-table tbody tr').count(), 100, 'Large tables render one bounded page');
    await shot('16-cross-source-correlations.png');
    for (const tab of ['Related Memory', 'Related Disk', 'Related Network']) {
      await navigate('processes'); await powerShell().click();
      await window.locator(`[data-process-tab="${tab}"]`).click();
      assert((await window.locator('#process-related-table tbody tr').count()) > 0);
      await shot(`17-process-${tab.split(' ')[1].toLowerCase()}.png`);
    }
    await navigate('correlations');
    await window.fill('#search', 'same_socket_tuple');
    await window.locator('#correlation-table tbody tr').first().click();
    assert.match(await window.locator('#inspector-content').innerText(), /same socket tuple/);
    await window.click('[data-inspector="provenance"]');
    assert.match(await window.locator('#inspector-content').innerText(), /frame:|flow:/);
    await shot('18-cross-source-provenance.png');
    await navigate('timeline');
    await window.selectOption('#timeline-source', 'disk');
    const diskRows = await window.locator('#timeline-table tbody tr').allTextContents();
    assert(diskRows.length > 0 && diskRows.every((row) => row.includes('DISK')));
    await window.selectOption('#timeline-source', '');
    await window.selectOption('#timeline-category', 'dns');
    assert.equal(await window.locator('#timeline-table tbody tr').count(), 2);
    await window.selectOption('#timeline-category', '');
    await shot('19-cross-source-timeline.png');
    await navigate('graph');
    await window.click('[data-graph-mode="entities"]');
    assert((await window.locator('.graph-node[data-kind="Domain"]').count()) > 0);
    assert((await window.locator('.graph-hit[aria-label^="OPENED"]').count()) > 0);
    assert((await window.locator('.graph-hit[aria-label^="EXECUTED"]').count()) > 0);
    await window.locator('.graph-hit[aria-label^="OPENED"]').first().focus(); await window.keyboard.press('Enter');
    assert.match(await window.locator('#inspector-content').innerText(), /FILE_OBJECT|File handle|file handle/);
    await shot('20-cross-source-entity-graph.png');
    await navigate('handles'); await window.locator('#evidence-table tbody tr').filter({ hasText: 'handle_observation' }).click();
    assert.match(await window.locator('#inspector-content').innerText(), /0xffff800000000123/);
    await window.click('[data-inspector="raw"]');
    assert((await window.locator('#inspector-content').innerText()).includes(BigInt('0xffff800000000123').toString()));
    await window.click('[data-inspector="overview"]');
    await shot('21-handles-64bit-address.png');
    await navigate('regions'); assert.equal(await window.locator('#evidence-table tbody tr').count(), 2);
    await shot('22-memory-regions.png');
    await navigate('event-logs'); assert.equal(await window.locator('#evidence-table tbody tr').count(), 9);
    await navigate('connections'); assert((await window.locator('#evidence-table tbody tr').count()) >= 4);
    await shot('23-network-flows.png');
    await window.click('#brand');
    const badCapture = path.join(temporary, 'invalid.pcap'); await writeFile(badCapture, 'Invalid capture fixture');
    await desktop.evaluate(({ dialog }, file) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [file] }); }, badCapture);
    await window.click('#import-network');
    await window.waitForFunction(() => document.querySelector('#status').textContent.includes('FAILED: imported 0'));
    await window.locator('#parser-runs-table tbody tr').filter({ hasText: 'FAILED' }).click();
    assert.match(await window.locator('#inspector-content').innerText(), /tshark exited/);
    await shot('24-parser-failure.png');
    assert.deepEqual(errors, []);
    console.log('PASS: baseline sample 16 links / 9 events; Volatility legacy import; actual Memory + five Disk artifacts + recovered file + PCAPNG imports; 67 events / 34 related; 28 successful parser runs; bounded 100-row tables; process memory/disk/network details; reasons/frame provenance; filtered timeline; typed graph; 64-bit handles; parser failure UI.');
  } finally {
    if (desktop) await desktop.close();
    if (backend.exitCode === null) {
      const exited = new Promise((resolve) => backend.once('exit', resolve));
      backend.kill();
      await exited;
    }
    await rm(temporary, { recursive: true, force: true });
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
