"""Synchronize distributable versions; --check fails instead of editing."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def synchronize(check=False):
    version = (ROOT / "VERSION").read_text().strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError("VERSION must contain a stable semantic version")
    outputs = {
        "engine/version.py": (
            '"""Generated by scripts/sync_version.py from the root VERSION file."""\n\n'
            f'VERSION = "{version}"\n'
        ),
        "desktop/src/version.ts": f'// Generated from VERSION.\nexport const VERSION = "{version}";\n',
    }
    for name in ("desktop/package.json", "desktop/package-lock.json"):
        data = json.loads((ROOT / name).read_text())
        data["version"] = version
        if "packages" in data:
            data["packages"][""]["version"] = version
        outputs[name] = json.dumps(data, indent=2) + "\n"
    outputs["pyproject.toml"] = re.sub(
        r'^version = "[^"]+"', f'version = "{version}"', (ROOT / "pyproject.toml").read_text(), flags=re.M
    )
    outputs["desktop/src/index.html"] = re.sub(
        r">0\.[34](?:\.\d+)?<", f">{version}<", (ROOT / "desktop/src/index.html").read_text()
    )
    mismatches = []
    for name, content in outputs.items():
        path = ROOT / name
        if not path.exists() or path.read_text() != content:
            mismatches.append(name)
            if not check:
                path.write_text(content, encoding="utf-8")
    if check and mismatches:
        raise SystemExit("Version mismatch: " + ", ".join(mismatches))
    print(f"Version {version}: {'verified' if check else 'synchronized'}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    synchronize(parser.parse_args().check)
